# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41b3b7988ac9fe318c71d88a123e1f1cec83ad823b5853f35e12d4f9e7d9fc60902aaf55b2831a62d6403de0af4d54840cb41190fdf9d5286200d9312696042d

test:
  secret_key_base: a702eae4e77684c00eca77495543d8616366d7d1d63d3f877deda45341302d8dfd6656c57d9787eaaea68a918dda3b1b1e584986b1d65760c036a8a3a26203ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
